### ISSUE TITLE
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by BDadmehr0** [BDadmehr0/OpenGameZone#3]
Traceback (most recent call last):
  File "/home/dadmehr/Documents/OpenGameZone/main.py", line 1, in <module>
    import customtkinter as ctk
  File "/home/dadmehr/.local/lib/python3.11/site-packages/customtkinter/__init__.py", line 5, in <module>
    from tkinter import Variable, StringVar, IntVar, DoubleVar, BooleanVar
  File "/usr/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory

**Comment by BDadmehr0** [comment]
[Answer](https://stackoverflow.com/questions/48504746/importerror-libtk8-6-so-cannot-open-shared-object-file-no-such-file-or-direct)
